### ISSUE TITLE
Executing from /tmp fails in CIS Hardened Linux

### ISSUE THREAD

**Issue by shederman** [diodonfrost/ansible-role-amazon-codedeploy#1]
When running this on a CIS Hardened Linux, the installation fails with:

`amzn-build: fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/tmp/codedeploy-install auto", "msg": "[Errno 13] Permission denied", "rc": 13}`

This is caused because `/tmp` is `noexec`. See https://www.cyberciti.biz/faq/linux-add-nodev-nosuid-noexec-options-to-temporary-storage-partitions/

Maybe put it somewhere else?

**Comment by diodonfrost** [comment]
@shederman Yeah, If `/tmp` is `noexec` this is not going to work.

I will add a variable to be able to change the destination folder for the installation script of codedeploy.

**Comment by diodonfrost** [comment]
Related [Fix](https://github.com/diodonfrost/ansible-role-amazon-codedeploy/commit/bcee6553554b95ea8aeb15f19dd3bb5592d60d65)

Now, You can set `codedeploy_install_script_dest` variable
```
---
- hosts: localhost
  become: true
  roles:
    - role: diodonfrost.amazon_codedeploy
      vars:
        codedeploy_install_script_dest: /var/tmp/codedeploy-install
```
